
# Builds and Deploys Storybook UI explorer to Azure WebApp
name: Build Storybook and Azure Web Publish

on: 
  push:
    branches:
      -main

env:
  AZURE_WEBAPP_NAME: ${{ secrets.STORYBOOK_AZURE_WEBAPP_NAME }}   # Azure Webapp Name
  AZURE_WEBAPP_PACKAGE_PATH: 'storybook-static' #Folder to deploy
  NODE_VERSION: '14.x' 

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build
      run: |
        npm install
        npm run build-storybook
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.STORYBOOK_AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
